# Generated by Django 4.1.7 on 2023-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorName", models.CharField(max_length=200)),
                ("doctorEmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("doctorProfileImg", models.ImageField(upload_to="doctorProfileImg")),
                ("specialization", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=200)),
                ("patientEmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("patientProfileImg", models.ImageField(upload_to="patientProfileImg")),
                ("symptoms", models.CharField(max_length=1000)),
                (
                    "assignedDoctorId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.doctor"
                    ),
                ),
            ],
        ),
    ]
