# Generated by Django 4.1.7 on 2023-06-10 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assignedDoctorId",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
