# Generated by Django 4.1.7 on 2023-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("HMS", "0002_remove_patient_assigneddoctorid_delete_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorName", models.CharField(max_length=200)),
                ("doctorEmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("doctorProfileImg", models.ImageField(upload_to="doctorProfileImg")),
                ("specialization", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=200)),
                ("patientEmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("patientProfileImg", models.ImageField(upload_to="patientProfileImg")),
                ("symptoms", models.CharField(max_length=1000)),
                (
                    "patientMedicalReport",
                    models.ImageField(
                        upload_to="patientMedicalReports/<int:Patient.pk>"
                    ),
                ),
                (
                    "assignedDoctorId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointmentDate", models.DateField(auto_now=True)),
                ("description", models.TextField(max_length=2000)),
                ("medicinePrescribed", models.CharField(max_length=1000)),
                ("appointmentCost", models.IntegerField(max_length=15)),
                ("wasAdmitted", models.BooleanField(default=False)),
                (
                    "doctorId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.doctor"
                    ),
                ),
                (
                    "patientId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmittedPatientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admittedOn", models.DateField()),
                ("dischargeDate", models.DateField()),
                ("roomCharges", models.IntegerField()),
                ("MedicineCost", models.IntegerField()),
                ("doctorFees", models.IntegerField()),
                ("otherCharges", models.IntegerField()),
                ("totalCost", models.IntegerField()),
                (
                    "appointmentDetailsId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HMS.appointment",
                    ),
                ),
                (
                    "doctorIdId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.doctor"
                    ),
                ),
                (
                    "patientId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HMS.patient"
                    ),
                ),
            ],
        ),
    ]
