# Generated by Django 4.1.7 on 2023-06-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="assignedDoctorId",
            new_name="currentlyAssignedDoctorId",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointmentCost",
            field=models.IntegerField(),
        ),
    ]
