# Generated by Django 4.1.7 on 2023-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "HMS",
            "0004_rename_assigneddoctorid_patient_currentlyassigneddoctorid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phonenumber", models.IntegerField()),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
    ]
