# Generated by Django 4.1.7 on 2023-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0007_alter_patient_patientusername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phonenumber",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.BigIntegerField(),
        ),
    ]
