# Generated by Django 4.1.7 on 2023-06-11 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0008_alter_doctor_phone_alter_feedback_phonenumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="patientUsername",
        ),
    ]
