# Generated by Django 4.1.7 on 2023-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0009_remove_patient_patientusername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patientProfileImg",
            field=models.ImageField(default="", upload_to="patientProfileImg"),
        ),
    ]
