# Generated by Django 4.1.7 on 2023-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0011_alter_patient_patientmedicalreport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="currentlyAssignedDoctorId",
            field=models.CharField(default="", max_length=8),
        ),
    ]
