# Generated by Django 4.1.7 on 2023-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0012_alter_patient_currentlyassigneddoctorid"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="availableOn",
            field=models.CharField(default="", max_length=10),
        ),
    ]
