# Generated by Django 4.1.7 on 2023-06-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0013_doctor_availableon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HMS.specialization"
            ),
        ),
    ]
