# Generated by Django 4.1.7 on 2023-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0014_specialization_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="specialization",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
