# Generated by Django 4.1.7 on 2023-06-12 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0015_alter_specialization_specialization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admittedpatientdetails",
            name="appointmentDetailsId",
        ),
        migrations.RemoveField(
            model_name="admittedpatientdetails",
            name="doctorIdId",
        ),
        migrations.RemoveField(
            model_name="admittedpatientdetails",
            name="patientId",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctorId",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patientId",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialization",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="AdmittedPatientDetails",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Specialization",
        ),
    ]
