# Generated by Django 4.1.7 on 2023-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0017_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="appointmentDetailsId",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
