# Generated by Django 4.1.7 on 2023-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0019_alter_admittedpatientdetails_appointmentdetailsid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientId", models.CharField(default="", max_length=10)),
                ("doctorIdId", models.CharField(default="", max_length=10)),
                ("appointmentDate", models.DateField(auto_now=True)),
                ("description", models.TextField(max_length=2000)),
                ("medicinePrescribed", models.CharField(max_length=1000)),
                ("appointmentCost", models.IntegerField()),
                ("wasAdmitted", models.BooleanField(default=False)),
            ],
        ),
    ]
