# Generated by Django 4.1.7 on 2023-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0020_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="doctorIdId",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="patientId",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctorIdId",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patientId",
            field=models.CharField(max_length=10),
        ),
    ]
