# Generated by Django 4.1.7 on 2023-06-12 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0021_alter_admittedpatientdetails_doctoridid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admittedpatientdetails",
            old_name="doctorIdId",
            new_name="doctorId",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="doctorIdId",
            new_name="doctorId",
        ),
    ]
