# Generated by Django 4.1.7 on 2023-06-13 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0023_remove_patient_symptoms_appointment_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointmentTime",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 6, 13, 5, 33, 38, 513887, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staust",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("COMPLETED", "COMPLETED")],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
