# Generated by Django 4.1.7 on 2023-06-13 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0024_appointment_appointmenttime_appointment_staust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointmentTime",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 6, 13, 5, 36, 48, 880002, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="medicinePrescribed",
            field=models.TextField(max_length=2000),
        ),
    ]
