# Generated by Django 4.1.7 on 2023-06-13 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0026_alter_appointment_appointmenttime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="staust",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointmentTime",
            field=models.TimeField(
                choices=[
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                ],
                default=datetime.datetime(
                    2023, 6, 13, 5, 40, 37, 438097, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
