# Generated by Django 4.1.7 on 2023-06-13 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0028_alter_appointment_appointmenttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointmentTime",
            field=models.DateTimeField(
                choices=[
                    ("10:00:00", "10:00:00"),
                    ("10:30:00", "10:30:00"),
                    ("11:00:00", "11:00:00"),
                    ("11:30:00", "11:30:00"),
                    ("12:00:00", "12:00:00"),
                    ("13:30:00", "13:30:00"),
                    ("15:00:00", "15:00:00"),
                    ("15:30:00", "15:30:00"),
                    ("16:00:00", "16:00:00"),
                    ("16:30:00", "16:30:00"),
                    ("17:00:00", "17:00:00"),
                    ("17:30:00", "17:30:00"),
                    ("18:00:00", "18:00:00"),
                    ("18:30:00", "18:30:00"),
                ],
                default=datetime.datetime(
                    2023, 6, 13, 12, 3, 48, 494305, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
