# Generated by Django 4.1.7 on 2023-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0032_alter_appointment_appointmenttime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="patientMedicalReport",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointmentTime",
            field=models.CharField(
                choices=[
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("13:30", "13:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                    ("18:00", "18:00"),
                    ("18:30", "18:30"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
