# Generated by Django 4.1.7 on 2023-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0033_remove_patient_patientmedicalreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminEmail", models.EmailField(max_length=254)),
                ("adminName", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=400)),
            ],
        ),
    ]
