# Generated by Django 4.1.7 on 2023-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0034_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="dischargeDate",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
