# Generated by Django 4.1.7 on 2023-06-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0036_alter_admittedpatientdetails_dischargedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admittedpatientdetails",
            name="doctorFees",
        ),
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="MedicineCost",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="otherCharges",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="roomCharges",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="admittedpatientdetails",
            name="totalCost",
            field=models.IntegerField(null=True),
        ),
    ]
