# Generated by Django 4.1.7 on 2023-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HMS", "0039_admittedpatientdetails_billstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmittedPatientCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admittedPatientDetailsId", models.CharField(max_length=100)),
                ("doctorVisitDate", models.DateField(auto_now=True)),
                ("patientCondition", models.TextField(max_length=2000)),
                ("newMedicinePrescribed", models.TextField(max_length=2000)),
            ],
        ),
    ]
